### ISSUE TITLE
Add combined eyelid parameter (for parameter opimization)

### ISSUE THREAD

**Issue by InsaneGrox** [benaclejames/VRCEyeTracking#20]
Idea: add combined eyelid parameters (left right and combined) that includes widening openness and squeezing...
EG: 0-0.2 = widen... 0.2-0.8=blink... 0.8-1.0 = squeeze...

Reason: To allow for more room for extra parameters with lip tracking.

**Comment by benaclejames** [comment]
![image](https://user-images.githubusercontent.com/11042095/115640698-794f2900-a30f-11eb-94b8-6d8f45af54da.png)
Combined parameters already exist, not sure if this is what you're suggesting

**Comment by InsaneGrox** [comment]
I was saying combine them even more... from what I've seen you cannot widen without your eyes being fully open... and you cannot squeeze without your eyes being fully closed...
therefore... have a combined parameter that combines them even more (mostly because you can have more than 2 animations on a 2d blend tree)

**Comment by benaclejames** [comment]
Ooo! Awesome idea!! I'll get to work on that very soon

**Comment by benaclejames** [comment]
Just committed a working version with the merging. Unfortunately, the squeeze data is often inaccurate and I'm yet to find anyone who actually uses it so I left it out of the merge. The new parameters are called "LeftEyeLidExpanded" and "RightEyeLidExpanded". Both scale blinking to 0-0.8 and widening to 0.8-1.

**Comment by benaclejames** [comment]
Added in pre-release. Will be in next full release.
https://github.com/benaclejames/VRCEyeTracking/releases/tag/v2.0.0a
