### ISSUE TITLE
Vive Wireless Disconnect

### ISSUE THREAD

**Issue by Adjerry91** [benaclejames/VRCEyeTracking#8]
I have ran into an issue with when Vive Wireless disconnects/resets with the Eye Tracking mod will fail to re-establish the eye tracking parameters. In order to reset the eye tracking have to restart the Melon loader/VR Chat to reestablish the port. This is fairly common with Vive Wireless when battery dies.  I have tried restarting the Tobii VRU02 Runtime service while in VRChat and still will not load the parameters.

**Comment by InconsolableCellist** [comment]
I have this same issue, but I think it's caused by SteamVR/Vive. When I get a disconnect/dead battery, if I go to the SteamVR menu and re-do eye-tracking calibration it'll fail to detect the device. I haven't tried restarting the runtime service though.
